import { FaUserTie } from "react-icons/fa";
import {
  AiOutlineDashboard,
  AiOutlineUser,
  AiOutlineCalendar,
  AiOutlineTeam,
  AiOutlineSchedule,
  AiOutlineForm,
  AiOutlineSafetyCertificate,
  AiOutlineBarChart,
  AiOutlineDollarCircle,
  AiOutlineTrophy,
  AiOutlineNotification,
  AiOutlineFileText,
  AiOutlineCustomerService,
  AiOutlineBook,
  AiOutlineComment,
  AiOutlineBell,
  AiOutlineApartment,
} from "react-icons/ai";

const employeeAccessRoles = [
  "EMPLOYEE",
  "MANAGER",
  "HR_ADMIN",
  "DIRECTOR",
  "ADMIN",
  "SUPER_ADMIN",
];

export const employeeNav = [
  //====================================
  //Employee Dashboard Navigation
  {
    title: "Employee",
    isGroupTitle: true,
    icon: <FaUserTie />,
    role: employeeAccessRoles,
  },
  {
    title: "Dashboard Overview",
    icon: <AiOutlineDashboard />,
    path: "/employee/dashboard",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "My Profile",
    icon: <AiOutlineUser />,
    path: "/employee/profile",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "My Attendance",
    icon: <AiOutlineCalendar />,
    path: "/employee/attendance",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "My Dependents",
    icon: <AiOutlineTeam />,
    path: "/employee/dependents",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "My Duty Schedule",
    icon: <AiOutlineSchedule />,
    path: "/employee/duty-schedule",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "My Leave Requests",
    icon: <AiOutlineForm />,
    path: "/employee/leave",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "My Licenses",
    icon: <AiOutlineSafetyCertificate />,
    path: "/employee/license",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "Performance Evaluation",
    icon: <AiOutlineBarChart />,
    path: "/employee/performance-evaluation",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "My Payroll",
    icon: <AiOutlineDollarCircle />,
    path: "/employee/payroll",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "Training & Certificates",
    icon: <AiOutlineTrophy />,
    path: "/employee/training",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "Announcements",
    icon: <AiOutlineNotification />,
    path: "/employee/announcements",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "Document Requests",
    icon: <AiOutlineFileText />,
    path: "/employee/documents",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "HR_ADMIN Helpdesk / Support Tickets",
    icon: <AiOutlineCustomerService />,
    path: "/employee/helpdesk",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "Company Policies / Handbook",
    icon: <AiOutlineBook />,
    path: "/employee/policies",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "Feedback or Suggestions",
    icon: <AiOutlineComment />,
    path: "/employee/feedback-suggestions",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "Task Reminders / Notifications",
    icon: <AiOutlineBell />,
    path: "/employee/notifications",
    role: employeeAccessRoles,
    group: "Employee",
  },
  {
    title: "Organization Chart",
    icon: <AiOutlineApartment />,
    path: "/employee/organization-chart",
    role: employeeAccessRoles,
    group: "Employee",
  },
];
